In [1]:
import math
import time
import csv
import os
os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"
os.environ['CUDA_VISIBLE_DEVICES']="1"
os.environ['CUDA_LAUNCH_BLOCKING'] = '1'

import numpy as np
import torch 
import torch.nn as nn
import torch.utils.data as data
import torch.nn.functional as F

torch.manual_seed(105)
np.random.seed(42)
np.set_printoptions(suppress=True, precision=3, threshold=40, linewidth=100, edgeitems=20)  

torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = True
#torch.backends.cudnn.enabled = False 
#Note:This cmd will lead to illegal memory runtime error (or sth. else concerning memory) if added...
#Note:But it doesn't hurt on the other server, and the other models... damns

import itertools
from tqdm import trange, tqdm
import matplotlib.pyplot as plt
import importlib
%matplotlib inline

'''
If curious about the detailed realization of certain module(s) below, try:
    print(*inspect.getsource(Module).split('\n'), sep='\n')
to get its source code.
'''
from Model.DeepCNN import ResNet
from Train.train_v1 import train
from Datas.data_load import dataset_append
from Test.Evaluate import evaluate
from utils.Save_and_load import save, load
from configs import opt, res_trans, RDevelop

In [2]:
def Model_def(opt, Channels, device_train, load_model):
    '''
    Define (and load saved) model 
    '''
    model = ResNet(Channels, bias=True)
    model.initialize()
    if load_model:
        model = load(model, opt.load_model_path)
    print(model.parameters)
    
    if device_train.type == 'cuda':
        torch.cuda.empty_cache()
        model = model.to(device_train)
        print("allocated and reserved GPU memory: {}, {} (GiB)".format(
                torch.cuda.memory_allocated()/(1024**3), torch.cuda.memory_reserved()/(1024**3)))
    return model

In [3]:
Channels = [2, 4, 6]
device_train = torch.device('cuda:0') 
device_test = torch.device('cuda:0')
ckpt_name = "ResNet.pth"
opt.load_model_path = opt.modelpath+ckpt_name
model = Model_def(opt, Channels, device_train, False)

Net Initialized
<bound method Module.parameters of ResNet(
  (conv1): Sequential(
    (0): Conv3d(1, 2, kernel_size=(3, 3, 3), stride=(1, 1, 1), padding=(1, 1, 1))
    (1): LeakyReLU(negative_slope=0.01, inplace=True)
  )
  (reslayers): Sequential(
    (0): Sequential(
      (0): BasicBlock(
        (conv): Sequential(
          (0): Conv3d(2, 2, kernel_size=(3, 3, 3), stride=(1, 1, 1), padding=(1, 1, 1), padding_mode=replicate)
          (1): LeakyReLU(negative_slope=0.01, inplace=True)
          (2): Conv3d(2, 2, kernel_size=(3, 3, 3), stride=(1, 1, 1), padding=(1, 1, 1), padding_mode=replicate)
        )
        (shortcut): Sequential()
      )
      (1): BasicBlock(
        (conv): Sequential(
          (0): Conv3d(2, 2, kernel_size=(3, 3, 3), stride=(1, 1, 1), padding=(1, 1, 1), padding_mode=replicate)
          (1): LeakyReLU(negative_slope=0.01, inplace=True)
          (2): Conv3d(2, 2, kernel_size=(3, 3, 3), stride=(1, 1, 1), padding=(1, 1, 1), padding_mode=replicate)
        )

In [4]:
dataset_train = dataset_append(opt, opt.dataidx_train, res_trans)
dataset_test = dataset_append(opt, opt.dataidx_test, res_trans) 

  0%|          | 0/8 [00:00<?, ?it/s]

../dataset_train_v1/0000Acid_ini Read in 0.70 s
../dataset_train_v1/0000Inhibitor Read in 0.73 s
--> Mask 0 Read Complete, with dataset size: (1, 1, 80, 1000, 1000), 9 masks left ...

../dataset_train_v1/0001Acid_ini Read in 0.72 s
../dataset_train_v1/0001Inhibitor Read in 0.69 s
--> Mask 1 Read Complete, with dataset size: (2, 1, 80, 1000, 1000), 8 masks left ...

../dataset_train_v1/0002Acid_ini Read in 0.68 s
../dataset_train_v1/0002Inhibitor Read in 0.70 s
--> Mask 2 Read Complete, with dataset size: (3, 1, 80, 1000, 1000), 7 masks left ...

../dataset_train_v1/0003Acid_ini Read in 0.71 s
../dataset_train_v1/0003Inhibitor Read in 0.68 s
--> Mask 3 Read Complete, with dataset size: (4, 1, 80, 1000, 1000), 6 masks left ...

../dataset_train_v1/0004Acid_ini Read in 0.71 s
../dataset_train_v1/0004Inhibitor Read in 0.72 s
--> Mask 4 Read Complete, with dataset size: (5, 1, 80, 1000, 1000), 5 masks left ...

../dataset_train_v1/0005Acid_ini Read in 0.72 s
../dataset_train_v1/0005Inhibito

 12%|█▎        | 1/8 [00:34<04:01, 34.49s/it]

--> Mask 9 Read Complete, with dataset size: (10, 1, 80, 1000, 1000), 0 masks left ...

../dataset_train_v1/0010Acid_ini Read in 0.73 s
../dataset_train_v1/0010Inhibitor Read in 0.73 s
--> Mask 10 Read Complete, with dataset size: (1, 1, 80, 1000, 1000), 9 masks left ...

../dataset_train_v1/0011Acid_ini Read in 0.70 s
../dataset_train_v1/0011Inhibitor Read in 0.72 s
--> Mask 11 Read Complete, with dataset size: (2, 1, 80, 1000, 1000), 8 masks left ...

../dataset_train_v1/0012Acid_ini Read in 0.75 s
../dataset_train_v1/0012Inhibitor Read in 0.73 s
--> Mask 12 Read Complete, with dataset size: (3, 1, 80, 1000, 1000), 7 masks left ...

../dataset_train_v1/0013Acid_ini Read in 0.67 s
../dataset_train_v1/0013Inhibitor Read in 0.69 s
--> Mask 13 Read Complete, with dataset size: (4, 1, 80, 1000, 1000), 6 masks left ...

../dataset_train_v1/0014Acid_ini Read in 0.75 s
../dataset_train_v1/0014Inhibitor Read in 0.67 s
--> Mask 14 Read Complete, with dataset size: (5, 1, 80, 1000, 1000), 5 mas

 25%|██▌       | 2/8 [01:09<03:28, 34.69s/it]

--> Mask 19 Read Complete, with dataset size: (10, 1, 80, 1000, 1000), 0 masks left ...

../dataset_train_v1/0020Acid_ini Read in 0.67 s
../dataset_train_v1/0020Inhibitor Read in 0.69 s
--> Mask 20 Read Complete, with dataset size: (1, 1, 80, 1000, 1000), 9 masks left ...

../dataset_train_v1/0021Acid_ini Read in 0.68 s
../dataset_train_v1/0021Inhibitor Read in 0.70 s
--> Mask 21 Read Complete, with dataset size: (2, 1, 80, 1000, 1000), 8 masks left ...

../dataset_train_v1/0022Acid_ini Read in 0.69 s
../dataset_train_v1/0022Inhibitor Read in 0.70 s
--> Mask 22 Read Complete, with dataset size: (3, 1, 80, 1000, 1000), 7 masks left ...

../dataset_train_v1/0023Acid_ini Read in 0.68 s
../dataset_train_v1/0023Inhibitor Read in 0.63 s
--> Mask 23 Read Complete, with dataset size: (4, 1, 80, 1000, 1000), 6 masks left ...

../dataset_train_v1/0024Acid_ini Read in 0.64 s
../dataset_train_v1/0024Inhibitor Read in 0.67 s
--> Mask 24 Read Complete, with dataset size: (5, 1, 80, 1000, 1000), 5 ma

 38%|███▊      | 3/8 [01:42<02:51, 34.21s/it]

--> Mask 29 Read Complete, with dataset size: (10, 1, 80, 1000, 1000), 0 masks left ...

../dataset_train_v1/0030Acid_ini Read in 0.62 s
../dataset_train_v1/0030Inhibitor Read in 0.67 s
--> Mask 30 Read Complete, with dataset size: (1, 1, 80, 1000, 1000), 9 masks left ...

../dataset_train_v1/0031Acid_ini Read in 0.69 s
../dataset_train_v1/0031Inhibitor Read in 0.66 s
--> Mask 31 Read Complete, with dataset size: (2, 1, 80, 1000, 1000), 8 masks left ...

../dataset_train_v1/0032Acid_ini Read in 0.64 s
../dataset_train_v1/0032Inhibitor Read in 0.68 s
--> Mask 32 Read Complete, with dataset size: (3, 1, 80, 1000, 1000), 7 masks left ...

../dataset_train_v1/0033Acid_ini Read in 0.68 s
../dataset_train_v1/0033Inhibitor Read in 0.64 s
--> Mask 33 Read Complete, with dataset size: (4, 1, 80, 1000, 1000), 6 masks left ...

../dataset_train_v1/0034Acid_ini Read in 0.64 s
../dataset_train_v1/0034Inhibitor Read in 0.65 s
--> Mask 34 Read Complete, with dataset size: (5, 1, 80, 1000, 1000), 5 ma

 50%|█████     | 4/8 [02:16<02:15, 33.85s/it]

--> Mask 39 Read Complete, with dataset size: (10, 1, 80, 1000, 1000), 0 masks left ...

../dataset_train_v1/0040Acid_ini Read in 0.67 s
../dataset_train_v1/0040Inhibitor Read in 0.70 s
--> Mask 40 Read Complete, with dataset size: (1, 1, 80, 1000, 1000), 9 masks left ...

../dataset_train_v1/0041Acid_ini Read in 0.68 s
../dataset_train_v1/0041Inhibitor Read in 0.69 s
--> Mask 41 Read Complete, with dataset size: (2, 1, 80, 1000, 1000), 8 masks left ...

../dataset_train_v1/0042Acid_ini Read in 0.67 s
../dataset_train_v1/0042Inhibitor Read in 0.69 s
--> Mask 42 Read Complete, with dataset size: (3, 1, 80, 1000, 1000), 7 masks left ...

../dataset_train_v1/0043Acid_ini Read in 0.67 s
../dataset_train_v1/0043Inhibitor Read in 0.66 s
--> Mask 43 Read Complete, with dataset size: (4, 1, 80, 1000, 1000), 6 masks left ...

../dataset_train_v1/0044Acid_ini Read in 0.65 s
../dataset_train_v1/0044Inhibitor Read in 0.63 s
--> Mask 44 Read Complete, with dataset size: (5, 1, 80, 1000, 1000), 5 ma

 62%|██████▎   | 5/8 [02:49<01:41, 33.74s/it]

--> Mask 49 Read Complete, with dataset size: (10, 1, 80, 1000, 1000), 0 masks left ...

../dataset_train_v1/0050Acid_ini Read in 0.69 s
../dataset_train_v1/0050Inhibitor Read in 0.68 s
--> Mask 50 Read Complete, with dataset size: (1, 1, 80, 1000, 1000), 9 masks left ...

../dataset_train_v1/0051Acid_ini Read in 0.63 s
../dataset_train_v1/0051Inhibitor Read in 0.63 s
--> Mask 51 Read Complete, with dataset size: (2, 1, 80, 1000, 1000), 8 masks left ...

../dataset_train_v1/0052Acid_ini Read in 0.14 s
../dataset_train_v1/0052Inhibitor Read in 0.13 s
--> Mask 52 Read Complete, with dataset size: (3, 1, 80, 1000, 1000), 7 masks left ...

../dataset_train_v1/0053Acid_ini Read in 0.13 s
../dataset_train_v1/0053Inhibitor Read in 0.12 s
--> Mask 53 Read Complete, with dataset size: (4, 1, 80, 1000, 1000), 6 masks left ...

../dataset_train_v1/0054Acid_ini Read in 0.13 s
../dataset_train_v1/0054Inhibitor Read in 0.12 s
--> Mask 54 Read Complete, with dataset size: (5, 1, 80, 1000, 1000), 5 ma

 75%|███████▌  | 6/8 [03:14<01:01, 30.72s/it]

--> Mask 59 Read Complete, with dataset size: (10, 1, 80, 1000, 1000), 0 masks left ...

../dataset_train_v1/0060Acid_ini Read in 0.12 s
../dataset_train_v1/0060Inhibitor Read in 0.12 s
--> Mask 60 Read Complete, with dataset size: (1, 1, 80, 1000, 1000), 9 masks left ...

../dataset_train_v1/0061Acid_ini Read in 0.12 s
../dataset_train_v1/0061Inhibitor Read in 0.11 s
--> Mask 61 Read Complete, with dataset size: (2, 1, 80, 1000, 1000), 8 masks left ...

../dataset_train_v1/0062Acid_ini Read in 0.11 s
../dataset_train_v1/0062Inhibitor Read in 0.11 s
--> Mask 62 Read Complete, with dataset size: (3, 1, 80, 1000, 1000), 7 masks left ...

../dataset_train_v1/0063Acid_ini Read in 0.12 s
../dataset_train_v1/0063Inhibitor Read in 0.13 s
--> Mask 63 Read Complete, with dataset size: (4, 1, 80, 1000, 1000), 6 masks left ...

../dataset_train_v1/0064Acid_ini Read in 0.12 s
../dataset_train_v1/0064Inhibitor Read in 0.11 s
--> Mask 64 Read Complete, with dataset size: (5, 1, 80, 1000, 1000), 5 ma

 88%|████████▊ | 7/8 [03:37<00:28, 28.05s/it]

--> Mask 69 Read Complete, with dataset size: (10, 1, 80, 1000, 1000), 0 masks left ...

../dataset_train_v1/0070Acid_ini Read in 0.12 s
../dataset_train_v1/0070Inhibitor Read in 0.11 s
--> Mask 70 Read Complete, with dataset size: (1, 1, 80, 1000, 1000), 9 masks left ...

../dataset_train_v1/0071Acid_ini Read in 0.12 s
../dataset_train_v1/0071Inhibitor Read in 0.11 s
--> Mask 71 Read Complete, with dataset size: (2, 1, 80, 1000, 1000), 8 masks left ...

../dataset_train_v1/0072Acid_ini Read in 0.12 s
../dataset_train_v1/0072Inhibitor Read in 0.11 s
--> Mask 72 Read Complete, with dataset size: (3, 1, 80, 1000, 1000), 7 masks left ...

../dataset_train_v1/0073Acid_ini Read in 0.11 s
../dataset_train_v1/0073Inhibitor Read in 0.11 s
--> Mask 73 Read Complete, with dataset size: (4, 1, 80, 1000, 1000), 6 masks left ...

../dataset_train_v1/0074Acid_ini Read in 0.11 s
../dataset_train_v1/0074Inhibitor Read in 0.12 s
--> Mask 74 Read Complete, with dataset size: (5, 1, 80, 1000, 1000), 5 ma

100%|██████████| 8/8 [03:59<00:00, 29.98s/it]


--> Mask 79 Read Complete, with dataset size: (10, 1, 80, 1000, 1000), 0 masks left ...



  0%|          | 0/2 [00:00<?, ?it/s]

../dataset_train_v1/0080Acid_ini Read in 0.68 s
../dataset_train_v1/0080Inhibitor Read in 0.69 s
--> Mask 80 Read Complete, with dataset size: (1, 1, 80, 1000, 1000), 9 masks left ...

../dataset_train_v1/0081Acid_ini Read in 0.69 s
../dataset_train_v1/0081Inhibitor Read in 0.66 s
--> Mask 81 Read Complete, with dataset size: (2, 1, 80, 1000, 1000), 8 masks left ...

../dataset_train_v1/0082Acid_ini Read in 0.68 s
../dataset_train_v1/0082Inhibitor Read in 0.70 s
--> Mask 82 Read Complete, with dataset size: (3, 1, 80, 1000, 1000), 7 masks left ...

../dataset_train_v1/0083Acid_ini Read in 0.68 s
../dataset_train_v1/0083Inhibitor Read in 0.68 s
--> Mask 83 Read Complete, with dataset size: (4, 1, 80, 1000, 1000), 6 masks left ...

../dataset_train_v1/0084Acid_ini Read in 0.65 s
../dataset_train_v1/0084Inhibitor Read in 0.64 s
--> Mask 84 Read Complete, with dataset size: (5, 1, 80, 1000, 1000), 5 masks left ...

../dataset_train_v1/0085Acid_ini Read in 0.65 s
../dataset_train_v1/0085Inh

 50%|█████     | 1/2 [00:33<00:33, 33.66s/it]

--> Mask 89 Read Complete, with dataset size: (10, 1, 80, 1000, 1000), 0 masks left ...

../dataset_train_v1/0090Acid_ini Read in 0.67 s
../dataset_train_v1/0090Inhibitor Read in 0.68 s
--> Mask 90 Read Complete, with dataset size: (1, 1, 80, 1000, 1000), 9 masks left ...

../dataset_train_v1/0091Acid_ini Read in 0.64 s
../dataset_train_v1/0091Inhibitor Read in 0.63 s
--> Mask 91 Read Complete, with dataset size: (2, 1, 80, 1000, 1000), 8 masks left ...

../dataset_train_v1/0092Acid_ini Read in 0.64 s
../dataset_train_v1/0092Inhibitor Read in 0.66 s
--> Mask 92 Read Complete, with dataset size: (3, 1, 80, 1000, 1000), 7 masks left ...

../dataset_train_v1/0093Acid_ini Read in 0.67 s
../dataset_train_v1/0093Inhibitor Read in 0.68 s
--> Mask 93 Read Complete, with dataset size: (4, 1, 80, 1000, 1000), 6 masks left ...

../dataset_train_v1/0094Acid_ini Read in 0.12 s
../dataset_train_v1/0094Inhibitor Read in 0.14 s
--> Mask 94 Read Complete, with dataset size: (5, 1, 80, 1000, 1000), 5 ma

100%|██████████| 2/2 [01:08<00:00, 34.19s/it]

--> Mask 99 Read Complete, with dataset size: (10, 1, 80, 1000, 1000), 0 masks left ...



In [5]:
def opt_strategy(model, opt):
    LR = 1e-3
    optimizer = torch.optim.Adam(model.parameters(), lr=LR,)# weight_decay=1e-4)
    scheduler = None
    #scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=100, eta_min=1e-4)
    scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=100, gamma=0.7)
    return optimizer, scheduler 

In [6]:
TotLoss = nn.MSELoss()
opt.epochs = 800
optimizer, scheduler = opt_strategy(model, opt)
train_log, test_log, lr_log = train(model, optimizer, scheduler, opt, dataset_train, device_train,
                                           dataset_test, res_trans, ckpt_name, TotLoss=TotLoss)
if not os.path.exists(opt.load_model_path):
    save(model, opt.modelpath, ckpt_name)

  0%|          | 1/800 [02:23<31:48:10, 143.29s/it]

Epoch 0 | LR: 1.00e-03 | Train Loss: 6.22e-02 | Test Loss: 1.54e+01, 4.72e-02, 97.12%


  3%|▎         | 21/800 [28:21<17:21:38, 80.23s/it]

Epoch 20 | LR: 1.00e-03 | Train Loss: 4.46e-03 | Test Loss: 1.82e+01, 7.45e-02, 98.85%


  5%|▌         | 41/800 [54:25<16:54:07, 80.17s/it]

Epoch 40 | LR: 1.00e-03 | Train Loss: 8.16e-03 | Test Loss: 2.11e+01, 7.04e-02, 99.75%


  8%|▊         | 61/800 [1:20:29<16:30:48, 80.44s/it]

Epoch 60 | LR: 1.00e-03 | Train Loss: 6.40e-03 | Test Loss: 2.11e+01, 6.13e-02, 99.75%


 10%|█         | 81/800 [1:46:35<16:03:50, 80.43s/it]

Epoch 80 | LR: 1.00e-03 | Train Loss: 7.51e-03 | Test Loss: 2.10e+01, 6.79e-02, 99.68%


 13%|█▎        | 101/800 [2:12:41<15:36:19, 80.37s/it]

Epoch 100 | LR: 7.00e-04 | Train Loss: 4.75e-03 | Test Loss: 1.99e+01, 7.07e-02, 99.39%


 15%|█▌        | 121/800 [2:38:46<15:09:11, 80.34s/it]

Epoch 120 | LR: 7.00e-04 | Train Loss: 1.61e-03 | Test Loss: 1.84e+01, 8.56e-02, 98.54%


 18%|█▊        | 141/800 [3:04:52<14:42:57, 80.39s/it]

Epoch 140 | LR: 7.00e-04 | Train Loss: 5.04e-03 | Test Loss: 1.72e+01, 5.07e-02, 97.35%


 20%|██        | 161/800 [3:30:59<14:18:28, 80.61s/it]

Epoch 160 | LR: 7.00e-04 | Train Loss: 3.35e-03 | Test Loss: 1.69e+01, 5.18e-02, 96.76%


 23%|██▎       | 181/800 [3:57:06<13:48:45, 80.33s/it]

Epoch 180 | LR: 7.00e-04 | Train Loss: 4.66e-03 | Test Loss: 1.66e+01, 7.86e-02, 95.97%


 25%|██▌       | 201/800 [4:23:11<13:23:03, 80.44s/it]

Epoch 200 | LR: 4.90e-04 | Train Loss: 2.39e-03 | Test Loss: 1.58e+01, 6.90e-02, 94.97%


 28%|██▊       | 221/800 [4:49:23<13:01:16, 80.96s/it]

Epoch 220 | LR: 4.90e-04 | Train Loss: 1.22e-03 | Test Loss: 1.50e+01, 5.36e-02, 93.56%


 30%|███       | 241/800 [5:15:20<12:24:41, 79.93s/it]

Epoch 240 | LR: 4.90e-04 | Train Loss: 3.34e-03 | Test Loss: 1.42e+01, 5.41e-02, 89.55%


 33%|███▎      | 261/800 [5:41:17<11:57:41, 79.89s/it]

Epoch 260 | LR: 4.90e-04 | Train Loss: 3.84e-03 | Test Loss: 1.31e+01, 5.24e-02, 86.99%


 35%|███▌      | 281/800 [6:07:15<11:31:49, 79.98s/it]

Epoch 280 | LR: 4.90e-04 | Train Loss: 1.65e-03 | Test Loss: 1.22e+01, 3.53e-02, 83.99%


 38%|███▊      | 301/800 [6:33:16<11:06:37, 80.15s/it]

Epoch 300 | LR: 3.43e-04 | Train Loss: 8.92e-04 | Test Loss: 1.23e+01, 5.58e-02, 81.35%


 40%|████      | 321/800 [6:59:18<10:40:32, 80.24s/it]

Epoch 320 | LR: 3.43e-04 | Train Loss: 7.36e-04 | Test Loss: 1.23e+01, 6.00e-02, 79.83%


 43%|████▎     | 341/800 [7:25:22<10:14:24, 80.31s/it]

Epoch 340 | LR: 3.43e-04 | Train Loss: 2.64e-03 | Test Loss: 1.20e+01, 5.20e-02, 78.77%


 45%|████▌     | 361/800 [7:51:25<9:47:22, 80.28s/it] 

Epoch 360 | LR: 3.43e-04 | Train Loss: 2.26e-03 | Test Loss: 1.19e+01, 4.44e-02, 77.78%


 48%|████▊     | 381/800 [8:17:28<9:20:39, 80.28s/it]

Epoch 380 | LR: 3.43e-04 | Train Loss: 2.26e-03 | Test Loss: 1.18e+01, 5.23e-02, 76.78%


 50%|█████     | 401/800 [8:43:32<8:53:49, 80.27s/it]

Epoch 400 | LR: 2.40e-04 | Train Loss: 2.47e-03 | Test Loss: 1.17e+01, 4.83e-02, 75.91%


 53%|█████▎    | 421/800 [9:09:35<8:27:12, 80.30s/it]

Epoch 420 | LR: 2.40e-04 | Train Loss: 6.05e-04 | Test Loss: 1.15e+01, 5.69e-02, 75.23%


 55%|█████▌    | 441/800 [9:35:39<8:00:01, 80.23s/it]

Epoch 440 | LR: 2.40e-04 | Train Loss: 6.09e-04 | Test Loss: 1.16e+01, 4.92e-02, 74.67%


 58%|█████▊    | 461/800 [10:01:41<7:33:16, 80.23s/it]

Epoch 460 | LR: 2.40e-04 | Train Loss: 1.20e-03 | Test Loss: 1.15e+01, 3.65e-02, 73.85%


 60%|██████    | 481/800 [10:27:45<7:06:43, 80.26s/it]

Epoch 480 | LR: 2.40e-04 | Train Loss: 5.56e-04 | Test Loss: 1.16e+01, 5.49e-02, 73.26%


 63%|██████▎   | 501/800 [10:53:48<6:39:35, 80.19s/it]

Epoch 500 | LR: 1.68e-04 | Train Loss: 9.32e-04 | Test Loss: 1.13e+01, 5.91e-02, 72.60%


 65%|██████▌   | 521/800 [11:19:50<6:12:41, 80.15s/it]

Epoch 520 | LR: 1.68e-04 | Train Loss: 2.65e-03 | Test Loss: 1.07e+01, 4.31e-02, 72.11%


 68%|██████▊   | 541/800 [11:45:51<5:46:21, 80.24s/it]

Epoch 540 | LR: 1.68e-04 | Train Loss: 2.64e-03 | Test Loss: 1.09e+01, 4.62e-02, 71.59%


 70%|███████   | 561/800 [12:11:54<5:19:34, 80.23s/it]

Epoch 560 | LR: 1.68e-04 | Train Loss: 2.00e-03 | Test Loss: 1.07e+01, 4.17e-02, 70.90%


 73%|███████▎  | 581/800 [12:37:57<4:52:54, 80.25s/it]

Epoch 580 | LR: 1.68e-04 | Train Loss: 1.54e-03 | Test Loss: 1.07e+01, 4.74e-02, 68.05%


 75%|███████▌  | 601/800 [13:03:59<4:25:52, 80.16s/it]

Epoch 600 | LR: 1.18e-04 | Train Loss: 4.64e-04 | Test Loss: 1.02e+01, 3.99e-02, 65.28%


 78%|███████▊  | 621/800 [13:29:59<3:58:44, 80.03s/it]

Epoch 620 | LR: 1.18e-04 | Train Loss: 4.74e-04 | Test Loss: 1.06e+01, 3.19e-02, 64.56%


 80%|████████  | 641/800 [13:56:03<3:32:58, 80.37s/it]

Epoch 640 | LR: 1.18e-04 | Train Loss: 1.39e-03 | Test Loss: 1.01e+01, 4.50e-02, 64.31%


 83%|████████▎ | 661/800 [14:22:07<3:05:56, 80.26s/it]

Epoch 660 | LR: 1.18e-04 | Train Loss: 1.55e-03 | Test Loss: 1.05e+01, 4.41e-02, 64.41%


 85%|████████▌ | 681/800 [14:48:10<2:39:06, 80.22s/it]

Epoch 680 | LR: 1.18e-04 | Train Loss: 9.02e-04 | Test Loss: 1.04e+01, 3.89e-02, 64.15%


 88%|████████▊ | 701/800 [15:14:15<2:12:29, 80.29s/it]

Epoch 700 | LR: 8.24e-05 | Train Loss: 9.64e-04 | Test Loss: 1.02e+01, 4.64e-02, 64.24%


 90%|█████████ | 721/800 [15:40:20<1:45:50, 80.39s/it]

Epoch 720 | LR: 8.24e-05 | Train Loss: 2.03e-03 | Test Loss: 1.03e+01, 3.56e-02, 64.12%


 93%|█████████▎| 741/800 [16:06:26<1:19:01, 80.36s/it]

Epoch 740 | LR: 8.24e-05 | Train Loss: 4.57e-04 | Test Loss: 1.04e+01, 4.52e-02, 64.05%


 95%|█████████▌| 761/800 [16:32:33<52:10, 80.27s/it]  

Epoch 760 | LR: 8.24e-05 | Train Loss: 1.95e-03 | Test Loss: 1.01e+01, 3.81e-02, 64.10%


 98%|█████████▊| 781/800 [16:58:38<25:24, 80.26s/it]

Epoch 780 | LR: 8.24e-05 | Train Loss: 4.87e-04 | Test Loss: 1.05e+01, 5.60e-02, 64.18%


100%|██████████| 800/800 [17:23:18<00:00, 78.25s/it]


In [4]:
model = Model_def(opt, Channels, device_train, True)
Runtime, RMSE, NMSE, _, CD_err_x, CD_err_y, CD_RMSE = evaluate(opt, model, device_train, res_trans, RDevelop)
print("Mean runtime:", np.mean(Runtime))
print("RMSE(Ihb, rate):", np.mean(RMSE,axis=-1))
print("NRMSE(Ihb, rate):", np.mean(NMSE,axis=-1))
print("CD Error(x, y):", np.mean(CD_RMSE,axis=-1))

Net Initialized
!Model load from  ./Ckpts/ResNet.pth
<bound method Module.parameters of ResNet(
  (conv1): Sequential(
    (0): Conv3d(1, 2, kernel_size=(3, 3, 3), stride=(1, 1, 1), padding=(1, 1, 1))
    (1): LeakyReLU(negative_slope=0.01, inplace=True)
  )
  (reslayers): Sequential(
    (0): Sequential(
      (0): BasicBlock(
        (conv): Sequential(
          (0): Conv3d(2, 2, kernel_size=(3, 3, 3), stride=(1, 1, 1), padding=(1, 1, 1), padding_mode=replicate)
          (1): LeakyReLU(negative_slope=0.01, inplace=True)
          (2): Conv3d(2, 2, kernel_size=(3, 3, 3), stride=(1, 1, 1), padding=(1, 1, 1), padding_mode=replicate)
        )
        (shortcut): Sequential()
      )
      (1): BasicBlock(
        (conv): Sequential(
          (0): Conv3d(2, 2, kernel_size=(3, 3, 3), stride=(1, 1, 1), padding=(1, 1, 1), padding_mode=replicate)
          (1): LeakyReLU(negative_slope=0.01, inplace=True)
          (2): Conv3d(2, 2, kernel_size=(3, 3, 3), stride=(1, 1, 1), padding=(1, 1, 

  0%|          | 0/20 [00:00<?, ?it/s]

../dataset_train_v1/0080Acid_ini Read in 0.12 s
../dataset_train_v1/0080Inhibitor Read in 0.12 s
RMSE for label 0: [0.01  0.866]
NMSE for label 0: [11.629  2.176]
NMSE_height for label 0: [12.403  1.916]


<<<
time:	0.435943s
<<<
<<<
time:	0.39695s
<<<



!Start to clear memory
CD_x error at height 0:
 [ 2.3    0.2    2.347  2.9    2.     1.83   2.1   -0.2    0.5    0.6    0.372 -0.     0.2    2.1
  0.8    0.2    0.3   -0.     1.4  ]
CD_y error at height 0:
 [-2.7    1.4    1.1    1.8    0.153  0.9    0.9    1.2   -0.1   -0.4    0.059  4.9   -0.7   -0.049
  0.575  0.2    0.2   -0.     0.3  ]
CD_x error at height 8:
 [-0.    -0.     1.6   -0.1    1.8    0.3    1.2   -0.1   -0.1    0.3   -0.4   -0.     0.5   -0.
  5.7    0.133 38.102 -0.2   -1.5    1.7  ]
CD_y error at height 8:
 [ 0.2   -0.6    1.318  1.5    0.461  2.346  0.941  2.     0.133  0.1   -0.818 -0.063  0.1   -0.1
 -0.1   -0.1    0.041  0.1    0.5  ]
CD_x error at height 16:
 [-0.2   -0.4    0.322  0.2   -0.    -0.079  0.5   -0.12   0.1    0.6    0.3    0.084  0.8    0.1
  0.1    0.237  0.2    0.9    2.   ]
CD_y error at height 16:
 [ 0.2   -0.9    0.313 -0.    -0.085 -0.3    0.1   -0.1   -0.9    0.946  0.18  -0.339  0.148 -1.063
  2.6   -0.133 -0.1    0.529  1.727]
CD_x error

  5%|▌         | 1/20 [2:10:58<41:28:36, 7858.77s/it]

Contact 18 in 72-CD_x_pred is redundant, with info [-952.883  928.096    5.786]
CD_x error at height 72:
 [1.8   0.9   2.226 1.2   1.    3.7   3.1   1.5   1.5   0.8   1.474 2.1   1.6   1.2   1.6   3.1
 1.454 3.867 5.786]
Contact 0 in 72-CD_y_pred is redundant, with info [-949.897  925.504    5.093]
CD_y error at height 72:
 [ 5.093  1.488 -1.189  1.119 -0.3    0.1   -0.4    0.579  0.    -0.4   -1.2   -0.1    0.6   -1.2
 -1.3   -0.6    0.    -1.2    0.958]
CD_RMSE for label 0: [3.168 1.077]
../dataset_train_v1/0081Acid_ini Read in 0.68 s
../dataset_train_v1/0081Inhibitor Read in 0.65 s
RMSE for label 1: [0.011 0.92 ]
NMSE for label 1: [11.53   2.315]
NMSE_height for label 1: [12.549  2.069]


<<<
time:	0.432812s
<<<



!Start to clear memory

!Start to clear memory


<<<
time:	0.400329s
<<<


CD_x error at height 0:
 [ 0.6    0.    -0.1    0.562  2.     0.5    1.3    0.2    0.1    0.3   -0.1    2.2    0.4    1.7
  0.076 -0.     0.444  0.2    0.1   -6.9  ]
CD_y error at height 0:
 [-5.3    2.3    0.552  3.651  0.508  0.457 -0.     2.2    1.     1.6    0.1   -0.306  0.155  0.1
  2.068  2.745  0.146  0.4    0.    -0.1  ]
CD_x error at height 8:
 [-0.9   -0.1    0.5    2.1   -1.3   -1.137  0.    -0.132 -0.032  1.3    0.3   -0.     1.     2.6
  0.222 -0.1    1.3   -0.506 -0.138  0.1  ]
CD_y error at height 8:
 [ 0.591 -0.352  0.472 -0.1   -0.6    0.1   -2.8    2.249 -0.2    2.4    0.1    0.155 -0.     0.2
  2.257  0.064 -0.    -0.    -2.2    0.1  ]
CD_x error at height 16:
 [-0.5    0.9   -0.    -0.116  1.844  1.3    1.3    0.578 -2.     0.9    2.5   -0.     0.728  0.2
 -1.7   -0.2    0.058 -0.7   -0.7    0.9  ]
CD_y error at height 16:
 [ 0.423  0.96  -0.224 -0.2   -0.1   -0.2   -0.301 -0.    -0.743  0.164  0.6   -0.27   1.6   -0.2
  0.2   -0.8    1.2    0.2    5.8    0.2  ]
CD

 10%|█         | 2/20 [4:21:43<39:15:10, 7850.56s/it]

Contact 19 in 72-CD_x_pred is redundant, with info [-958.198  939.397    8.   ]
CD_x error at height 72:
 [2.033 1.2   1.6   0.8   0.9   2.2   0.5   2.9   2.312 2.6   2.4   2.5   1.    0.8   1.2   1.6
 2.9   1.758 2.    8.   ]
Contact 0 in 72-CD_y_pred is redundant, with info [-954.198  934.651    9.646]
CD_y error at height 72:
 [ 9.646  0.834  0.1   -1.1   -3.135 -0.4    1.3    0.5   -0.204  0.7    1.1   -0.805  1.     3.359
  0.237 -1.06  -0.466  0.011 -0.524  0.2  ]
CD_RMSE for label 1: [1.657 1.744]
../dataset_train_v1/0082Acid_ini Read in 0.14 s
../dataset_train_v1/0082Inhibitor Read in 0.14 s
RMSE for label 2: [0.006 0.532]
NMSE for label 2: [11.262  1.334]
NMSE_height for label 2: [12.141  1.146]

!Start to clear memory


<<<
time:	0.408389s
<<<



!Start to clear memory


<<<
time:	0.363559s
<<<


CD_x error at height 0:
 [ 0.2    1.8    0.473  0.206  0.    -0.2    0.2   -0.1  ]
CD_y error at height 0:
 [ 0.13  0.13 -0.   -0.6   2.    0.3  -0.    2.  ]
CD_x error at height 8:
 [ 0.4 -0.5 -0.  -0.   0.1  0.3 -0.  -0.6]
CD_y error at height 8:
 [-0.   0.1  0.4  0.1  2.3  3.1  2.1 -1. ]
CD_x error at height 16:
 [ 0.026  0.9    0.4    0.477 -0.161 -0.1    0.846  2.1  ]
CD_y error at height 16:
 [ 0.1    0.5   -0.3    0.454 -0.035  0.274  0.9    0.4  ]
CD_x error at height 24:
 [-1.5    1.9   -0.2   -0.    -0.    -0.616 -0.     0.1  ]
CD_y error at height 24:
 [ 0.1   -0.    -0.    -0.2    0.914 -1.1    0.3    0.8  ]
CD_x error at height 32:
 [ 2.7 -0.1  0.3 -0.  -0.4  0.2 -0.   0. ]
CD_y error at height 32:
 [ 0.6   -0.191 -0.1   -0.     0.912  0.2   -0.1    5.   ]
CD_x error at height 40:
 [-0.3    2.14   1.1    0.2   -0.6    0.9    0.391  0.5  ]
CD_y error at height 40:
 [ 0.334 -0.3   -0.     0.2    1.75  -1.1    0.2   -0.9  ]
CD_x error at height 48:
 [ 1.8   -0.1   -1.242 -2.1

 15%|█▌        | 3/20 [6:31:27<36:55:40, 7820.02s/it]

CD_x error at height 72:
 [1.661 1.718 2.154 0.7   0.7   2.974 2.37  1.2  ]
CD_y error at height 72:
 [ 1.1    0.7    0.798 -0.168  0.2    1.5    0.6   -0.8  ]
CD_RMSE for label 2: [1.125 1.033]
../dataset_train_v1/0083Acid_ini Read in 0.14 s
../dataset_train_v1/0083Inhibitor Read in 0.14 s
RMSE for label 3: [0.009 0.756]
NMSE for label 3: [11.48   1.898]
NMSE_height for label 3: [12.126  1.644]

!Start to clear memory


<<<
time:	0.420997s
<<<



!Start to clear memory


<<<
time:	0.384283s
<<<


CD_x error at height 0:
 [ 2.175 -0.1   -0.     0.062  0.427  1.5   -0.1    0.9    0.541  0.101 -0.1    0.3   -0.572  1.8
  0.509]
CD_y error at height 0:
 [ 0.097  0.7   -0.196  0.4   -0.4    0.1    0.9    0.7   -0.     0.6    0.2    1.5    0.8   -0.
 -0.021]
CD_x error at height 8:
 [-0.2   -0.207 -0.    -0.     1.2    0.753  1.1    0.3    0.489  0.9   -1.     0.1    0.1    0.9
  1.7  ]
CD_y error at height 8:
 [-0.751 -0.264  0.459 -0.653  0.     1.    -0.21   0.618  2.5    2.239 -0.     0.7    0.9   -0.3
 -0.1  ]
CD_x error at height 16:
 [-0.1   -0.25   0.1    1.     0.2    1.7    2.2   -1.1    0.785 -0.1    1.1    3.     0.383 -0.1
 -0.3  ]
CD_y error at height 16:
 [-0.1    0.2   -1.9    0.4    0.2    0.7   -0.195  0.2   -0.1   -0.1    2.1    0.3   -3.2    2.254
  1.3  ]
CD_x error at height 24:
 [ 0.2   -0.595 -0.1   -0.1    0.1   -1.2    1.2   -3.4   -0.701  0.3   -0.9   -0.     0.7   -0.1
 -0.2  ]
CD_y error at height 24:
 [ 0.264 -1.8    1.4   -0.4    1.2    0.343 -1.8    1.

 20%|██        | 4/20 [8:40:49<34:39:15, 7797.19s/it]

CD_x error at height 72:
 [1.258 2.324 1.416 1.142 1.394 0.8   3.6   1.1   2.9   1.2   1.3   1.    5.    1.7   2.5  ]
CD_y error at height 72:
 [-0.2    0.567 -0.1    0.1    1.5    0.062  0.4    0.1    0.756  0.041 -0.5   -0.255  0.452 -0.249
  0.039]
CD_RMSE for label 3: [1.388 1.027]
../dataset_train_v1/0084Acid_ini Read in 0.14 s
../dataset_train_v1/0084Inhibitor Read in 0.13 s
RMSE for label 4: [0.004 0.353]
NMSE for label 4: [11.332  0.882]
NMSE_height for label 4: [12.186  0.778]

!Start to clear memory


<<<
time:	0.39257s
<<<



!Start to clear memory


<<<
time:	0.376009s
<<<


CD_x error at height 0:
 [ 2.4  1.2 -0. ]
CD_y error at height 0:
 [-0.    -0.041  0.1  ]
CD_x error at height 8:
 [ 0.4 -1.1  0.6]
CD_y error at height 8:
 [ 0.056  0.387 -0.   ]
CD_x error at height 16:
 [-0.8  0.2 -0. ]
CD_y error at height 16:
 [ 0.532 -2.76   0.119]
CD_x error at height 24:
 [0.2 2.1 0.1]
CD_y error at height 24:
 [-0.6    0.174 -0.4  ]
CD_x error at height 32:
 [-0.2   -0.059 -0.   ]
CD_y error at height 32:
 [ 0.1   -0.314  4.   ]
CD_x error at height 40:
 [-0.     0.594  1.445]
CD_y error at height 40:
 [0.11  0.    0.505]
CD_x error at height 48:
 [-1.545 -0.5    1.608]
CD_y error at height 48:
 [-0.2 -0.5  0.1]
CD_x error at height 56:
 [ 0.2 -1.6  1.5]
CD_y error at height 56:
 [ 0.971 -0.1   -0.   ]
CD_x error at height 64:
 [0.2 1.2 2.3]
CD_y error at height 64:
 [ 0.5 -0.  -0. ]


 25%|██▌       | 5/20 [10:49:59<32:25:01, 7780.10s/it]

CD_x error at height 72:
 [0.5   2.453 2.3  ]
CD_y error at height 72:
 [0.006 0.2   0.066]
CD_RMSE for label 4: [1.224 0.941]
../dataset_train_v1/0085Acid_ini Read in 0.14 s
../dataset_train_v1/0085Inhibitor Read in 0.13 s
RMSE for label 5: [0.008 0.651]
NMSE for label 5: [11.959  1.633]
NMSE_height for label 5: [12.52   1.429]

!Start to clear memory


<<<
time:	0.418985s
<<<



!Start to clear memory


<<<
time:	0.400391s
<<<


CD_x error at height 0:
 [ 0.5  0.1 -0.1  0.4  0.1  0.8  3.2  1.5 -0.9 -0.6]
CD_y error at height 0:
 [ 0.255  0.5    0.2    0.847  2.6   -1.     0.3   -0.2    0.2   -0.   ]
CD_x error at height 8:
 [-0.     0.9    0.541 -0.     2.1   -0.     2.1    1.4    0.3   -0.   ]
CD_y error at height 8:
 [ 0.1   -0.3    2.9    0.343  3.063 -0.9    1.345 -0.4    0.5    0.1  ]
CD_x error at height 16:
 [ 2.5    0.2   -0.5   -1.    -0.    -0.9    1.1    1.827 -0.1    1.3  ]
CD_y error at height 16:
 [ 0.2    1.    -0.265  0.2    0.1    1.03   3.     1.7    0.3    1.4  ]
CD_x error at height 24:
 [ 0.1 -0.4  1.   2.4 -0.   0.  -1.1 -0.1  0.8 -0.9]
CD_y error at height 24:
 [-0.1   -0.057 -1.3    0.6    0.894 -2.54  -1.8   -1.1   -0.2    0.3  ]
CD_x error at height 32:
 [-0.1 -0.1 -0.1  0.6 -0.   0.8 -2.6  1.1  0.   0.7]
CD_y error at height 32:
 [ 0.406  0.085 -0.4   -2.2    0.7    0.6    2.25   1.9   -0.1    0.154]
CD_x error at height 40:
 [ 0.761 -0.1   -0.5   -0.     1.     1.8    0.264  1.8   -

 30%|███       | 6/20 [12:59:16<30:13:31, 7772.22s/it]

CD_x error at height 72:
 [1.1   2.313 1.    0.7   0.6   1.1   2.    0.9   1.1   0.7  ]
CD_y error at height 72:
 [-2.    -0.8   -1.562 -0.    -0.3   -2.5    0.472 -0.535 -0.4    0.1  ]
CD_RMSE for label 5: [1.25  1.132]
../dataset_train_v1/0086Acid_ini Read in 0.13 s
../dataset_train_v1/0086Inhibitor Read in 0.13 s
RMSE for label 6: [0.004 0.416]
NMSE for label 6: [13.861  1.04 ]
NMSE_height for label 6: [15.884  1.004]


<<<
time:	0.399025s
<<<



!Start to clear memory


<<<
time:	0.343961s
<<<



!Start to clear memory
CD_x error at height 0:
 [ 2.2    0.553 -7.4  ]
CD_y error at height 0:
 [-8.191  1.753  0.044]
CD_x error at height 8:
 [-0.4    0.     0.224]
CD_y error at height 8:
 [-0.155  1.328  0.1  ]
CD_x error at height 16:
 [0.4 2.1 0.8]
CD_y error at height 16:
 [ 1.5   -0.024  0.946]
CD_x error at height 24:
 [-0.1    0.129 -3.1  ]
CD_y error at height 24:
 [ 0.    -0.595  0.8  ]
CD_x error at height 32:
 [2.1 1.4 0.2]
CD_y error at height 32:
 [-0.  -0.2 -0. ]
CD_x error at height 40:
 [-1.8  0.7  3. ]
CD_y error at height 40:
 [-0.5  2.1  1.3]
CD_x error at height 48:
 [-0.7  0.1  7.1]
CD_y error at height 48:
 [ 4.4   -0.164  1.1  ]
CD_x error at height 56:
 [-0.3 -0.6  3.7]
CD_y error at height 56:
 [ 9.7  0.1 -0. ]
CD_x error at height 64:
 [2.646 1.1   7.8  ]
CD_y error at height 64:
 [12.368 -0.107 -2.1  ]


 35%|███▌      | 7/20 [15:08:26<28:02:27, 7765.21s/it]

Contact 2 in 72-CD_x_pred is redundant, with info [-963.798   79.854    6.9  ]
Contact 3 in 72-CD_x_pred is redundant, with info [-961.479   87.354    1.481]
CD_x error at height 72:
 [3.167 0.7   6.9   1.481]
Contact 0 in 72-CD_y_pred is redundant, with info [-960.498   73.754   13.701]
CD_y error at height 72:
 [13.701  0.2   -1.08 ]
CD_RMSE for label 6: [3.051 4.256]
../dataset_train_v1/0087Acid_ini Read in 0.13 s
../dataset_train_v1/0087Inhibitor Read in 0.13 s
RMSE for label 7: [0.004 0.343]
NMSE for label 7: [11.172  0.857]
NMSE_height for label 7: [12.101  0.75 ]

!Start to clear memory


<<<
time:	0.379651s
<<<
<<<
time:	0.345021s
<<<



!Start to clear memory
CD_x error at height 0:
 [ 1.5 -0.  -0. ]
CD_y error at height 0:
 [0.2   0.248 0.069]
CD_x error at height 8:
 [ 2.6 -0.   0.3]
CD_y error at height 8:
 [-0.5 -0.6  0.5]
CD_x error at height 16:
 [-0.4    0.358 -1.324]
CD_y error at height 16:
 [ 1.3 -0.2 -0.3]
CD_x error at height 24:
 [ 0.9    2.6   -1.561]
CD_y error at height 24:
 [ 0.1    0.213 -0.4  ]
CD_x error at height 32:
 [ 1.4   -0.084 -0.098]
CD_y error at height 32:
 [-0.228  0.     1.4  ]
CD_x error at height 40:
 [ 0.8   -0.289 -0.069]
CD_y error at height 40:
 [-0.249 -0.148  0.965]
CD_x error at height 48:
 [-0.   -0.05 -0.8 ]
CD_y error at height 48:
 [-0.    -0.069 -0.1  ]
CD_x error at height 56:
 [-0.614 -1.9   -0.8  ]
CD_y error at height 56:
 [ 0.  -0.2  0. ]
CD_x error at height 64:
 [2.8 0.2 1.1]
CD_y error at height 64:
 [-0.3 -0.2  0.1]


 40%|████      | 8/20 [17:17:35<25:51:59, 7760.00s/it]

CD_x error at height 72:
 [3.36  1.7   2.787]
CD_y error at height 72:
 [ 0.5  1.  -1.4]
CD_RMSE for label 7: [1.416 0.561]
../dataset_train_v1/0088Acid_ini Read in 0.13 s
../dataset_train_v1/0088Inhibitor Read in 0.13 s
RMSE for label 8: [0.006 0.464]
NMSE for label 8: [10.874  1.161]
NMSE_height for label 8: [11.708  0.986]

!Start to clear memory


<<<
time:	0.392643s
<<<



!Start to clear memory


<<<
time:	0.369651s
<<<


CD_x error at height 0:
 [-0.     1.    -0.     0.469  0.5   -0.1  ]
CD_y error at height 0:
 [ 0.     1.751  0.143  0.857 -0.6    0.4  ]
CD_x error at height 8:
 [ 2.5    0.8    0.5    2.3   -0.     0.448]
CD_y error at height 8:
 [ 1.2   -0.2    0.226 -0.1    1.8    1.441]
CD_x error at height 16:
 [-0.7  0.4 -0.1 -0.2 -0.   0.2]
CD_y error at height 16:
 [ 0.     0.6    1.083 -2.65  -0.     2.04 ]
CD_x error at height 24:
 [ 2.2 -0.3  2.8 -0.   1.2  0. ]
CD_y error at height 24:
 [-0.1    0.67   1.257 -0.022  1.1   -0.2  ]
CD_x error at height 32:
 [ 0.3 -0.1  2.1  0.4  2.   1.4]
CD_y error at height 32:
 [-0.2   -0.2   -0.346 -0.2    0.44   0.8  ]
CD_x error at height 40:
 [ 0.1   -0.431 -0.1   -0.    -0.5    0.075]
CD_y error at height 40:
 [-0.    -0.226 -0.1   -0.1    0.4    2.8  ]
CD_x error at height 48:
 [ 0.1   -1.115 -1.6   -1.6    2.3    0.2  ]
CD_y error at height 48:
 [-0.1   -0.6    1.3   -0.1   -0.7    0.952]
CD_x error at height 56:
 [-0.1 -0.9 -0.1 -0.3 -0.1  0.1]
CD

 45%|████▌     | 9/20 [19:26:48<23:42:13, 7757.63s/it]

CD_x error at height 72:
 [1.176 1.2   1.2   1.9   0.9   1.676]
CD_y error at height 72:
 [ 0.059  0.9    0.2    0.5   -1.1   -0.222]
CD_RMSE for label 8: [1.162 0.914]
../dataset_train_v1/0089Acid_ini Read in 0.13 s
../dataset_train_v1/0089Inhibitor Read in 0.13 s
RMSE for label 9: [0.006 0.523]
NMSE for label 9: [11.243  1.311]
NMSE_height for label 9: [12.06  1.13]


<<<
time:	0.421217s
<<<



!Start to clear memory


<<<
time:	0.376467s
<<<



!Start to clear memory
CD_x error at height 0:
 [ 0.2  -0.2   0.28  0.2   1.1   2.3   0.3 ]
CD_y error at height 0:
 [ 0.2  1.7  1.9 -0.1  0.8  0.3  0.1]
CD_x error at height 8:
 [ 0.6    1.4   -0.204 -0.8   -0.    -0.1   -0.   ]
CD_y error at height 8:
 [ 1.753  1.213  0.878  0.487 -0.224 -0.3    0.1  ]
CD_x error at height 16:
 [ 0.6    1.852 -0.1   -0.8    0.5    1.3   -0.1  ]
CD_y error at height 16:
 [-0.4    0.404 -0.8   -0.8   -0.155  2.205  0.7  ]
CD_x error at height 24:
 [-0.   1.5  0.2 -0.1  1.8  0.2 -0. ]
CD_y error at height 24:
 [ 0.9    0.455 -1.    -0.     1.6   -0.002 -0.6  ]
CD_x error at height 32:
 [ 0.1  1.  -0.2 -0.   0.1  0.6  0.2]
CD_y error at height 32:
 [ 0.1    0.12   0.2    0.145  0.2    0.1   -0.145]
CD_x error at height 40:
 [ 0.1 -0.5  0.1 -2.1  0.4 -0.1 -0. ]
CD_y error at height 40:
 [-1.   2.2 -1.3  2.   1.   2.   0.4]
CD_x error at height 48:
 [-0.2 -0.9 -0.2 -1.1 -0.   0.6  0.6]
CD_y error at height 48:
 [-0.1   -0.1   -0.155 -0.133 -0.1    1.9    

 50%|█████     | 10/20 [21:36:02<21:32:44, 7756.50s/it]

CD_x error at height 72:
 [1.  1.6 2.  1.1 1.4 2.4 0.6]
CD_y error at height 72:
 [-1.8   -1.2    0.559 -1.3    0.526 -0.917 -0.2  ]
CD_RMSE for label 9: [1.074 0.899]
../dataset_train_v1/0090Acid_ini Read in 0.12 s
../dataset_train_v1/0090Inhibitor Read in 0.12 s
RMSE for label 10: [0.007 0.56 ]
NMSE for label 10: [11.613  1.404]
NMSE_height for label 10: [12.54   1.232]

!Start to clear memory


<<<
time:	0.393158s
<<<



!Start to clear memory


<<<
time:	0.367741s
<<<


CD_x error at height 0:
 [ 1.8   -0.1   -0.    -0.     0.196  2.5   -0.1    0.7  ]
CD_y error at height 0:
 [ 2.1   -0.3    0.3    0.3    0.992 -0.3    0.1    0.1  ]
CD_x error at height 8:
 [ 0.018 -1.3    0.5    0.835 -0.124 -0.2   -0.293  2.1  ]
CD_y error at height 8:
 [-0.4    0.762  1.773  0.9    1.7    0.2   -0.2   -0.1  ]
CD_x error at height 16:
 [-1.2    3.2    0.2    0.2    0.     3.     0.213  0.3  ]
CD_y error at height 16:
 [-0.1    0.554 -0.1    0.5   -0.2    4.1    1.724  0.1  ]
CD_x error at height 24:
 [ 0.1   -1.3    0.184 -0.    -0.2   -0.     0.5   -0.5  ]
CD_y error at height 24:
 [-0.067 -1.7    1.7   -0.1    2.9   -0.     0.3   -0.   ]
CD_x error at height 32:
 [-0.     0.2    1.343  0.2    0.    -0.379 -0.7   -0.2  ]
CD_y error at height 32:
 [ 0.1    0.5   -0.051 -0.7    0.11   1.854  0.706  0.001]
CD_x error at height 40:
 [-0.071  1.8    0.048 -0.3    0.79   0.8   -1.2    2.   ]
CD_y error at height 40:
 [-0.143  0.1    0.853  0.1   -1.    -2.9    0.003  0.9

 55%|█████▌    | 11/20 [23:45:18<19:23:28, 7756.54s/it]

CD_x error at height 72:
 [1.   1.8  2.75 2.4  3.9  1.   1.2  1.74]
CD_y error at height 72:
 [ 0.025  0.1   -0.2    0.827 -0.1    0.563  1.3    0.1  ]
CD_RMSE for label 10: [1.285 1.048]
../dataset_train_v1/0091Acid_ini Read in 0.12 s
../dataset_train_v1/0091Inhibitor Read in 0.12 s
RMSE for label 11: [0.008 0.666]
NMSE for label 11: [11.599  1.671]
NMSE_height for label 11: [12.254  1.451]

!Start to clear memory


<<<
time:	0.409042s
<<<



!Start to clear memory


<<<
time:	0.391339s
<<<


CD_x error at height 0:
 [-0.3    0.004 -0.2    0.045 -0.2    0.3    0.894  0.028  0.1    1.9   -0.043]
CD_y error at height 0:
 [ 1.156 -0.     2.523  0.5   -0.6    0.236 -0.2    1.978  1.4    0.791  1.9  ]
CD_x error at height 8:
 [ 0.6   -0.157  0.4   -0.3    0.1    0.5   -0.     1.6   -0.1   -0.4    1.7  ]
CD_y error at height 8:
 [ 0.074  0.244  0.002 -0.666  2.392  0.433  1.341  1.4    0.084 -0.     1.8  ]
CD_x error at height 16:
 [-0.     2.129  0.1    0.1    1.2    1.8    0.1    2.    -0.1    3.3    1.9  ]
CD_y error at height 16:
 [ 0.9   -0.    -0.3   -1.1   -2.4   -0.1   -0.067 -0.246  0.     1.6    1.8  ]
CD_x error at height 24:
 [ 1.073  1.2   -0.    -0.2   -0.2    3.3    2.2    0.1   -0.     0.6   -0.2  ]
CD_y error at height 24:
 [-0.4    0.2    0.8    0.3   -1.9    2.141 -0.306 -0.8    0.7    1.1   -0.   ]
CD_x error at height 32:
 [ 0.037 -0.559 -0.1   -0.2    1.2   -1.2    0.    -0.2   -0.1    0.1    0.2  ]
CD_y error at height 32:
 [ 0.2    0.125  0.1    0.1   -0.4

 60%|██████    | 12/20 [25:54:36<17:14:13, 7756.74s/it]

CD_x error at height 72:
 [2.    1.121 0.8   1.6   1.7   1.    2.5   1.65  2.4   1.6   4.595]
CD_y error at height 72:
 [ 1.1    0.296 -0.3   -0.8   -0.25   0.071 -0.3   -0.2   -0.    -0.655 -2.1  ]
CD_RMSE for label 11: [1.306 0.917]
../dataset_train_v1/0092Acid_ini Read in 0.11 s
../dataset_train_v1/0092Inhibitor Read in 0.12 s
RMSE for label 12: [0.005 0.424]
NMSE for label 12: [11.441  1.062]
NMSE_height for label 12: [12.575  0.917]


<<<
time:	0.382507s
<<<



!Start to clear memory

!Start to clear memory


<<<
time:	0.36404s
<<<


CD_x error at height 0:
 [ 2.4    0.1    1.1   -0.075  0.498]
CD_y error at height 0:
 [-0.448  2.2    1.994 -0.     0.646]
CD_x error at height 8:
 [-0.4 -0.4  0.4 -0.3  0.1]
CD_y error at height 8:
 [ 0.2    0.498  0.325 -1.197  0.1  ]
CD_x error at height 16:
 [-0.5    0.694 -0.     0.2    1.9  ]
CD_y error at height 16:
 [-0.131  0.9    0.045  2.6   -0.4  ]
CD_x error at height 24:
 [-0.1  0.1  1.5 -0.   0.2]
CD_y error at height 24:
 [-1.751 -0.     1.8   -1.2   -1.5  ]
CD_x error at height 32:
 [-0.9    0.47   0.361 -1.9    0.1  ]
CD_y error at height 32:
 [-0.1    0.35   1.851 -0.6   -0.3  ]
CD_x error at height 40:
 [-0.1   -1.     0.4    1.    -1.055]
CD_y error at height 40:
 [-0.1   -0.029 -0.    -0.2   -0.1  ]
CD_x error at height 48:
 [-0.1   -0.    -0.1   -0.5    0.503]
CD_y error at height 48:
 [-0.1 -0.5  0.1 -0.1 -0. ]
CD_x error at height 56:
 [ 2.6  0.9  1.1  2.3 -0.3]
CD_y error at height 56:
 [ 1.328 -0.4   -0.     0.595 -0.4  ]
CD_x error at height 64:
 [3.    3.6

 65%|██████▌   | 13/20 [28:03:48<15:04:48, 7755.52s/it]

CD_x error at height 72:
 [1.207 3.5   0.8   2.7   1.1  ]
CD_y error at height 72:
 [0.05  2.    0.283 0.033 0.415]
CD_RMSE for label 12: [1.396 0.926]
../dataset_train_v1/0093Acid_ini Read in 0.12 s
../dataset_train_v1/0093Inhibitor Read in 0.11 s
RMSE for label 13: [0.008 0.629]
NMSE for label 13: [11.569  1.578]
NMSE_height for label 13: [12.165  1.342]


<<<
time:	0.415773s
<<<



!Start to clear memory


<<<
time:	0.368036s
<<<



!Start to clear memory
CD_x error at height 0:
 [ 0.1    1.2    0.3   -0.3   -0.    -0.2    1.    -0.349 -0.2    1.5    0.1  ]
CD_y error at height 0:
 [ 4.9    0.2    0.    -0.187  0.355  1.564  0.5   -0.3    0.4   -0.     0.82 ]
CD_x error at height 8:
 [ 0.1    0.271  0.2    0.     0.3   -0.4   -0.3    0.6    0.4    0.4   -0.4  ]
CD_y error at height 8:
 [-0.    -0.     0.047  0.317  2.9    0.363 -0.6    0.1    1.    -0.2    0.361]
CD_x error at height 16:
 [-0.3    0.9    0.1    0.     0.7    0.     0.6    2.3   -0.2   38.602 -0.    -0.   ]
CD_y error at height 16:
 [ 0.1    0.6    2.     0.4   -0.238  1.2   -0.712 -0.508  0.898 -0.133 -0.5  ]
CD_x error at height 24:
 [ 0.2    1.8   -1.3   -0.1    0.1    0.1    0.301  0.1    0.2   -0.1   -0.1  ]
CD_y error at height 24:
 [-0.3    0.1    2.338  0.8   -0.    -0.2   -0.634 -0.1    3.     1.654 -0.   ]
CD_x error at height 32:
 [-0.8  -1.2  -1.1   0.3   0.2   0.5   0.3  -0.   -0.8   1.   -0.03]
CD_y error at height 32:
 [-0.157  0.1 

 70%|███████   | 14/20 [30:13:07<12:55:38, 7756.37s/it]

CD_x error at height 72:
 [2.3   1.3   2.246 1.8   2.3   3.1   3.6   1.4   3.2   1.4   2.7  ]
CD_y error at height 72:
 [ 0.7    0.5    0.6   -0.5   -0.    -0.94  -1.243  0.2    0.182  0.188  1.   ]
CD_RMSE for label 13: [3.842 0.954]
../dataset_train_v1/0094Acid_ini Read in 0.12 s
../dataset_train_v1/0094Inhibitor Read in 0.13 s
RMSE for label 14: [0.013 0.98 ]
NMSE for label 14: [15.229  2.461]
NMSE_height for label 14: [16.348  2.256]

!Start to clear memory


<<<
time:	0.42742s
<<<
<<<
time:	0.399969s
<<<



!Start to clear memory
Contact 12 in 0-CD_x_pred is redundant, with info [651.12  704.585  25.664]
CD_x error at height 0:
 [ 1.5    1.3    0.503 -0.2   -0.1    0.518  2.5    0.     0.     1.9   -0.027  3.3   25.664  0.5
 -0.     0.2    0.4  ]
Contact 13 in 0-CD_y_pred is redundant, with info [663.983 690.485  26.301]
CD_y error at height 0:
 [  0.9    -0.1     0.1     0.048   3.1     0.1    -0.3     0.96    0.3     0.3     3.6    -0.1
 -38.502  26.301 -20.601   0.996  -0.1     0.1     0.1  ]
Contact 12 in 8-CD_x_pred is redundant, with info [654.383 703.585  20.401]
CD_x error at height 8:
 [  0.3    -0.1    -1.393   0.     -0.7    -0.633   0.042   2.     -0.1     1.5     0.1    -0.4
  20.401   0.1     0.6     2.331   1.    -25.694 -35.133]
CD_y error at height 8:
 [ 0.047  1.2    0.711 -0.349 -0.045 -1.6   -0.2    1.    -1.02  -0.1    2.     3.757 38.359 38.459
 38.659 21.758 -0.192  0.063 -0.364 -0.3  ]
CD_x error at height 16:
 [-0.    -0.8   -0.    -0.1   -0.1    0.133  0.6    2.

 75%|███████▌  | 15/20 [32:22:25<10:46:25, 7757.12s/it]

CD_x error at height 72:
 [0.8   2.2   1.    1.8   3.53  1.4   1.9   3.518 2.5   2.8   2.4   2.951 3.5   3.2   1.4  ]
CD_y error at height 72:
 [ 1.     0.361 -0.7   -1.1   -2.4   -0.3   -0.    -0.3   -0.    -0.8   -0.3    1.1   -0.2   -0.9
 -0.493]
CD_RMSE for label 14: [5.216 8.571]
../dataset_train_v1/0095Acid_ini Read in 0.13 s
../dataset_train_v1/0095Inhibitor Read in 0.13 s
RMSE for label 15: [0.009 0.755]
NMSE for label 15: [11.566  1.896]
NMSE_height for label 15: [12.187  1.658]

!Start to clear memory


<<<
time:	0.425195s
<<<



!Start to clear memory


<<<
time:	0.384276s
<<<


CD_x error at height 0:
 [ 0.     0.086  1.8    0.405 -0.179 -0.     0.412  0.052  1.706  0.5    0.2    0.1    0.044]
CD_y error at height 0:
 [ 0.355  0.2    0.617  6.2    0.2    0.355  0.1    0.8    2.5    0.5   -0.352  0.     3.9  ]
CD_x error at height 8:
 [ 0.9    0.3    1.9   -0.     0.275  0.477 -1.1    0.1    0.438 -0.1    0.2    2.     1.5  ]
CD_y error at height 8:
 [-0.1    1.023  1.84   0.058  1.868 -0.118  2.8   -1.268  0.156 -0.2   -0.248  0.9    6.   ]
CD_x error at height 16:
 [-1.9    0.2   -0.123  1.     1.8    0.1   -0.2    0.1   -0.4   -0.1    1.9    0.5    1.8   38.602]
CD_y error at height 16:
 [ 0.054  0.1    0.243 -0.2    0.2   -0.214  0.738  1.5    0.144  0.2    0.354 -0.846  2.9  ]
CD_x error at height 24:
 [-0.554  0.8   -0.8    1.1   -1.7    1.3    0.467  0.6   -1.7    0.2   -0.3   -0.     0.   ]
CD_y error at height 24:
 [ 1.888 -0.     0.317  0.463  0.4    2.9   -0.2   -0.237  0.038 -0.2    0.5    0.1    0.381]
CD_x error at height 32:
 [ 1.4   -0.213 -1.2

 80%|████████  | 16/20 [34:31:46<8:37:12, 7758.01s/it] 

CD_x error at height 72:
 [1.2   1.3   1.4   1.699 1.1   1.7   0.9   1.673 2.599 1.763 0.9   1.    3.1  ]
CD_y error at height 72:
 [-1.133  0.9   -0.3    0.3    0.349 -0.511 -0.5   -0.2   -0.1   -0.    -0.7   -1.8    0.1  ]
CD_RMSE for label 15: [3.541 1.182]
../dataset_train_v1/0096Acid_ini Read in 0.14 s
../dataset_train_v1/0096Inhibitor Read in 0.14 s
RMSE for label 16: [0.011 0.947]
NMSE for label 16: [11.547  2.384]
NMSE_height for label 16: [12.384  2.088]


<<<
time:	0.417359s
<<<



!Start to clear memory

!Start to clear memory


<<<
time:	0.378606s
<<<


CD_x error at height 0:
 [ 1.1   -2.1    0.2   -0.    -0.383  1.7    0.6    0.8   -0.1    2.1   -1.    -0.1    1.5   -0.038
  1.    -0.02   0.5    1.     0.    -0.1    0.1   -0.     1.2  ]
CD_y error at height 0:
 [ 6.115 38.217 38.317 38.117  0.1    0.672  1.22  -0.9   -0.8    0.16  -0.6   -0.    -0.2    0.119
  2.5   -0.134  0.021  1.801  3.4    1.4   -0.1    1.456  2.     1.4   -3.7    0.1  ]
CD_x error at height 8:
 [ 1.2    1.4   -0.3    0.1   -0.     1.5    4.708 -0.339  0.757  2.8    1.2    2.2   -2.     1.5
  2.3   -0.1   -3.6    0.9    3.    -0.     0.1    0.3    1.9  ]
CD_y error at height 8:
 [-0.266 -0.     0.045 -0.1    0.3   -0.4    0.764  0.2    0.8    0.8    0.266  3.7   -0.2    0.512
  3.849 -0.248  1.3   -0.1    2.5   -0.6   -0.049 -0.     1.   ]
CD_x error at height 16:
 [ 2.3    0.6    0.2    0.247 -0.     0.2    1.3    0.    -2.    -0.    -0.087 -0.009 -0.5    0.5
 -0.223  0.1   -0.5    0.     0.2    0.    -0.     0.1   -1.2  ]
CD_y error at height 16:
 [ 0.1    0.

 85%|████████▌ | 17/20 [36:41:13<6:28:02, 7760.89s/it]

CD_x error at height 72:
 [1.9   1.    1.4   1.    1.1   1.7   1.841 1.666 2.296 3.6   3.2   1.6   3.3   1.7   0.451 2.3
 2.363 2.6   3.6   1.6   1.2   4.43 ]
CD_y error at height 72:
 [-0.1    0.2   -0.158  0.5    4.581  0.5    0.421 -0.7    0.5   -0.     0.3   -1.2    0.763  0.1
  1.7   -0.6   -0.567 -0.6   -1.3   -1.    -1.25   3.7  ]
CD_RMSE for label 16: [1.463 4.512]
../dataset_train_v1/0097Acid_ini Read in 0.13 s
../dataset_train_v1/0097Inhibitor Read in 0.12 s
RMSE for label 17: [0.01  0.813]
NMSE for label 17: [11.468  2.042]
NMSE_height for label 17: [12.299  1.788]

!Start to clear memory


<<<
time:	0.433162s
<<<
<<<
time:	0.387271s
<<<



!Start to clear memory
CD_x error at height 0:
 [ 0.1    0.199  0.1    0.2    2.034  1.66   0.1    3.1    1.4   -0.02  -0.464 -0.     0.2   -0.
 -0.    -0.395  2.1  ]
CD_y error at height 0:
 [-0.    -0.7    0.8   -0.     0.011  2.2    0.707  1.209  0.3    0.6    0.157  3.3    0.396  0.7
  0.4    0.069  1.3  ]
CD_x error at height 8:
 [ 0.1   -0.553 -0.604  0.1    0.8   -0.207  0.3   -1.3    3.2   -0.5    0.1    0.1    1.9   -0.8
  0.1    0.5    0.7  ]
CD_y error at height 8:
 [-0.66  -0.     0.8   -0.    -0.5    0.129  2.3    0.    -0.1   -0.1    1.783  2.2    1.5    0.762
  0.052 -0.136  0.13 ]
CD_x error at height 16:
 [-0.1    0.384  0.326  0.4    1.1    0.1   -0.1    0.9    1.55  -0.4   -0.6   -0.     1.8   -0.5
  0.034  1.9    1.2  ]
CD_y error at height 16:
 [-0.3   -0.471  4.    38.302  0.435  0.184 -0.174  3.5    0.2    0.     2.1   -0.228  0.177  0.34
  1.6    1.916  0.1    1.8  ]
CD_x error at height 24:
 [-0.    -0.427  0.4    1.435  0.     0.1    1.4    0.1   -0.1    0.1 

 90%|█████████ | 18/20 [38:50:37<4:18:43, 7761.74s/it]

CD_x error at height 72:
 [3.223 1.736 0.9   1.9   1.6   0.8   2.692 2.    0.6   1.3   1.805 1.1   3.115 2.077 0.9   1.3
 1.8  ]
CD_y error at height 72:
 [ 0.352  0.336 -0.7   -0.623 -0.548  0.824 -1.2   -0.     2.388 -0.5    2.3   -0.6   -0.8    1.633
 -1.612 -0.667  0.3  ]
CD_RMSE for label 17: [1.242 3.133]
../dataset_train_v1/0098Acid_ini Read in 0.13 s
../dataset_train_v1/0098Inhibitor Read in 0.12 s
RMSE for label 18: [0.011 0.91 ]
NMSE for label 18: [11.662  2.287]
NMSE_height for label 18: [12.432  2.011]


<<<
time:	0.413901s
<<<



!Start to clear memory

!Start to clear memory


<<<
time:	0.395828s
<<<


Contact 19 in 0-CD_x_label is redundant, with info [348.867 879.694   5.8  ]
CD_x error at height 0:
 [ 1.5    0.507 -0.1    0.327  0.9    2.2    0.1    0.865  0.974  0.3   38.376  0.9    1.2    0.1
 -0.088  0.2   -0.144 -0.     1.231 -5.8    0.2  ]
Contact 13 in 0-CD_y_label is redundant, with info [351.268 873.694  11.101]
CD_y error at height 0:
 [  0.1     2.118   3.2    -0.5     2.979   0.141   0.4     0.1     1.018   0.27    0.4     0.2
   2.2   -11.101  -0.067  -0.059   0.618   0.3    -0.1     2.6  ]
CD_x error at height 8:
 [ 0.739  0.5    0.5    0.099  0.624  2.084 -0.1    1.4    1.1    1.3   -0.6    0.041  0.3    1.6
 -0.2    0.283  0.2    0.142  4.7    7.941 -0.1  ]
CD_y error at height 8:
 [-0.1   -1.615  0.516  3.341  0.425  0.142  0.3    0.2    0.3   -0.    -0.639 -0.1    9.612  0.049
  0.255  0.3   -0.3    0.9    0.2   -0.3  ]
Contact 18 in 16-CD_x_pred is redundant, with info [350.934 875.894   6.534]
CD_x error at height 16:
 [ 0.    -0.     0.2   -1.634 -0.2   -1.03  

 95%|█████████▌| 19/20 [41:00:05<2:09:23, 7763.81s/it]

CD_x error at height 72:
 [0.6   1.304 0.648 1.3   3.3   2.    2.4   1.5   2.1   1.3   1.2   1.2   2.    2.4   2.8   1.1
 1.4   2.3   3.9  ]
CD_y error at height 72:
 [ 0.8   -1.424 -1.6   -0.4   -1.3   -1.     2.464 -1.157 -0.4    0.065  0.5   -0.2   -0.708 -0.3
  0.4   -0.     1.    -0.592 -1.138]
CD_RMSE for label 18: [3.105 3.18 ]
../dataset_train_v1/0099Acid_ini Read in 0.13 s
../dataset_train_v1/0099Inhibitor Read in 0.13 s
RMSE for label 19: [0.005 0.463]
NMSE for label 19: [11.332  1.159]
NMSE_height for label 19: [12.058  1.031]

!Start to clear memory


<<<
time:	0.413853s
<<<



!Start to clear memory


<<<
time:	0.365029s
<<<


CD_x error at height 0:
 [1.7 1.5 1.6 2.3 0.2]
CD_y error at height 0:
 [0.7   0.232 0.416 0.228 2.   ]
CD_x error at height 8:
 [ 0.3  0.4  0.5 -0.   0.1]
CD_y error at height 8:
 [ 0.4   -1.43  -0.2    0.038  0.043]
CD_x error at height 16:
 [ 1.7  3.3 -0.9  0.  -0.2]
CD_y error at height 16:
 [-1.3   -0.1    0.94  -0.    -0.562]
CD_x error at height 24:
 [ 0.2   -0.4   -0.1   -0.8   -0.127]
CD_y error at height 24:
 [-0.8    1.328 -3.3    2.5    1.   ]
CD_x error at height 32:
 [-1.2 -2.1 -0.1 -0.  -1. ]
CD_y error at height 32:
 [ 0.1    1.3   -0.029 -0.7   -0.2  ]
CD_x error at height 40:
 [-0.242 -0.2   -0.6    0.1   -2.1  ]
CD_y error at height 40:
 [ 1.8 -0.2 -2.   0.2 -1.3]
CD_x error at height 48:
 [ 0.5    0.535 -0.1   -0.    -1.01 ]
CD_y error at height 48:
 [ 1.    1.8  -1.1  -0.6  -0.05]
CD_x error at height 56:
 [ 0.9    0.652  0.9   -0.     0.465]
CD_y error at height 56:
 [-0.3   0.44  0.   -0.5  -0.02]
CD_x error at height 64:
 [-0.5   1.2  -0.    0.07  2.9 ]
CD_y err

100%|██████████| 20/20 [43:10:01<00:00, 7770.08s/it]  

CD_x error at height 72:
 [2.7 2.6 3.6 4.  2.8]
CD_y error at height 72:
 [-0.1    0.324  0.1   -0.954 -0.5  ]
CD_RMSE for label 19: [1.453 1.041]
CD Error: [2.018 1.952]
RMSE(Mean, Std): [0.008 0.649] [0.003 0.204]
NMSE(Mean, Std): [11.768  1.628] [0.975 0.514]
NMSE_height: [[22.967 17.961 15.726 17.647 17.234 15.744 14.335 13.242 12.314 11.476 10.712 10.021  9.403
   8.853  8.368  7.944  7.574  7.253  6.977  6.739 ...  8.858  9.563 10.412 11.422 12.609 13.99
  15.576 17.382 19.42  21.708 24.256 27.117 30.418 33.727 35.032 33.216 33.269 43.312 59.734
  73.982]
 [ 3.401  2.692  2.314  2.682  2.67   2.483  2.303  2.161  2.036  1.918  1.807  1.703  1.606
   1.518  1.441  1.373  1.313  1.26   1.214  1.174 ...  0.955  0.928  0.912  0.905  0.925  0.97
   1.028  1.102  1.187  1.271  1.358  1.444  1.526  1.528  1.19   0.882  2.148  3.428  4.358
   4.943]]
Top Error (mean): [39.406  2.28 ]


Mean runtime: 1.7660516500473022
RMSE(Ihb, rate): [0.008 0.649]
NRMSE(Ihb, rate): [11.768  1.628]
CD Error(x, y): [2.018 1.952]


In [ ]:
Err_x, Err_y = np.array([]), np.array([])
for tmp in range(len(CD_err_x)):
    Err_x = np.append(Err_x, np.array(CD_err_x[tmp]).flatten())
    Err_y = np.append(Err_y, np.array(CD_err_y[tmp]).flatten())

np.savetxt(opt.respath+"CDErr-x_deepCNN.csv", Err_x.flatten(), delimiter=' ')
np.savetxt(opt.respath+"CDErr-y_deepCNN.csv", Err_y.flatten(), delimiter=' ')
from utils.Res_plot import CD_errXY_plot
CD_errXY_plot(Err_x, Err_y, "DeePCNN's ")